### ISSUE TITLE
[WSL] Build on linux 

### ISSUE THREAD

**Issue by Ddiidev** [tryphotino/photino.Native#130]
When trying to compile the template application, this returns me. I have installed .NET 8,7 and 6.
I used the project in both versions and it doesn't work.

![image](https://github.com/tryphotino/photino.Native/assets/7676415/8474b22c-732c-47c5-9527-99c16ec1f9c2)

```
andre@Nitro5:/mnt/e/source/MyPhotinoApp$ dotnet add package Photino.Native --version 2.6.0


  Determining projects to restore...
  Writing /tmp/tmpwMmMWx.tmp
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/lib/dotnet/sdk/8.0.104/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/lib/dotnet/sdk/8.0.104/trustedroots/timestampctl.pem'.
info : Adding PackageReference for package 'Photino.Native' into project '/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj'.
info : Restoring packages for /mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj...
info :   CACHE https://api.nuget.org/v3/vulnerabilities/index.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.25.01.10.39/vulnerability.base.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.25.01.10.39/2024.04.25.13.10.40/vulnerability.update.json
info : Package 'Photino.Native' is compatible with all the specified frameworks in project '/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj'.
info : PackageReference for package 'Photino.Native' version '2.6.0' updated in file '/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj'.
info : Writing assets file to disk. Path: /mnt/e/source/MyPhotinoApp/obj/project.assets.json
log  : Restored /mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj (in 142 ms).


andre@Nitro5:/mnt/e/source/MyPhotinoApp$ dotnet add package Photino.NET --version 2.6.0


  Determining projects to restore...
  Writing /tmp/tmpkg0u7v.tmp
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/lib/dotnet/sdk/8.0.104/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/lib/dotnet/sdk/8.0.104/trustedroots/timestampctl.pem'.
info : Adding PackageReference for package 'Photino.NET' into project '/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj'.
info : Restoring packages for /mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj...
info :   CACHE https://api.nuget.org/v3/vulnerabilities/index.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.25.01.10.39/vulnerability.base.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.25.01.10.39/2024.04.25.13.10.40/vulnerability.update.json
info : Package 'Photino.NET' is compatible with all the specified frameworks in project '/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj'.
info : PackageReference for package 'Photino.NET' version '2.6.0' updated in file '/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj'.
info : Assets file has not changed. Skipping assets file writing. Path: /mnt/e/source/MyPhotinoApp/obj/project.assets.json
log  : Restored /mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj (in 138 ms).


andre@Nitro5:/mnt/e/source/MyPhotinoApp$ dotnet run


/mnt/e/source/MyPhotinoApp/Program.cs(43,52): warning CS8622: Nullability of reference types in type of parameter 'sender' of 'lambda expression' doesn't match the target delegate 'EventHandler<string>' (possibly because of nullability attributes). [/mnt/e/source/MyPhotinoApp/HelloPhotino.NET.csproj]
Photino.NET: "Photino".SetTitle(Photino for .NET Demo App)
Photino.NET: "Photino for .NET Demo App".SetUseOsDefaultSize(False)
Photino.NET: "Photino for .NET Demo App".SetSize({Width=600, Height=400})
Photino.NET: "Photino for .NET Demo App".Center()
Photino.NET: "Photino for .NET Demo App".SetResizable(False)
Photino.NET: "Photino for .NET Demo App".Load(wwwroot/index.html)
Photino.NET: "Photino for .NET Demo App".Load(file:///mnt/e/source/MyPhotinoApp/wwwroot/index.html)
Photino.NET: "Photino for .NET Demo App"***
Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
libnotify.so.4: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/Photino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/Photino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/runtimes/linux-x64/native/libPhotino.Native.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/libPhotino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/libPhotino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/runtimes/linux-x64/native/Photino.Native: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/Photino.Native: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/Photino.Native: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/runtimes/linux-x64/native/libPhotino.Native: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/libPhotino.Native: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/libPhotino.Native: cannot open shared object file: No such file or directory

   at PhotinoNET.PhotinoWindow.Photino_ctor(PhotinoNativeParameters& parameters)
   at PhotinoNET.PhotinoWindow.<WaitForClose>b__352_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow.WaitForClose()
Error #0
Unhandled exception. System.ApplicationException: Native code exception. Error # 0  See inner exception for details.
 ---> System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
libnotify.so.4: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/Photino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/Photino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/runtimes/linux-x64/native/libPhotino.Native.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/libPhotino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/libPhotino.Native.so: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/runtimes/linux-x64/native/Photino.Native: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/Photino.Native: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/Photino.Native: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/runtimes/linux-x64/native/libPhotino.Native: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.4/libPhotino.Native: cannot open shared object file: No such file or directory
/mnt/e/source/MyPhotinoApp/bin/Debug/net8.0/libPhotino.Native: cannot open shared object file: No such file or directory

   at PhotinoNET.PhotinoWindow.Photino_ctor(PhotinoNativeParameters& parameters)
   at PhotinoNET.PhotinoWindow.<WaitForClose>b__352_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow.WaitForClose()
   --- End of inner exception stack trace ---
   at PhotinoNET.PhotinoWindow.WaitForClose()
   at HelloPhotinoApp.Program.Main(String[] args) in /mnt/e/source/MyPhotinoApp/Program.cs:line 56
andre@Nitro5:/mnt/e/source/MyPhotinoApp$
```

**Comment by Ddiidev** [comment]
The problem was about Linux not having permission to access my E drive:
After I add the project in, ex: `%userprofile%\source\repos`
everything worked perfectly.

Sorry for the inconvenience!

**Comment by MikeYeager** [comment]
@Ddiidev Great to hear! Thanks for letting us know.
