### ISSUE TITLE
System.DllNotFoundException on Win7 

### ISSUE THREAD

**Issue by whgfu** [tryphotino/photino.Native#135]
This program is directly compiled using a demo. Under. net8, the compiled program works normally on both win10 and win11, but win7 prompts System DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies, But I can confirm that my directory contains Photino The Native.dll file.

May I ask how to handle this issue?

Application: HelloPhotino.NET.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: 找不到指定的程序。 (0x8007007F)
   at Photino.NET.PhotinoWindow.<Photino_register_win32>g____PInvoke|1_0(IntPtr __hInstance_native)
   at Photino.NET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
   at Photino.NET.PhotinoWindow.<>c.<.ctor>b__309_0()
   at Photino.NET.PhotinoWindow.Invoke(Action workItem)
   at Photino.NET.PhotinoWindow..ctor(PhotinoWindow parent)
   at HelloPhotinoApp.Program.Main(String[] args) in C:\Users\bimvr\Desktop\tmp\MyPhotinoApp\Program.cs:line 70

**Comment by MikeYeager** [comment]
@whgfu Are you running 64-bit Windows 7?

**Comment by whgfu** [comment]
> @whgfu Are you running 64-bit Windows 7?

Yes,64 bit  win7

**Comment by philippjbauer** [comment]
Hi @whgfu, please use the Fusion Log Viewer to determine which DLL exactly creates the issue and provide this information to us. https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

**Comment by Huochengyan** [comment]
I encountered the same issue.
![image](https://github.com/user-attachments/assets/33527ddf-6a8b-491e-8917-b1390f53949e)

**Comment by MikeYeager** [comment]
Please use the Fusion Log Viewer tool as mentioned above to determine what is missing. We don't support out of support OSs, but if you can determine what's not loading correctly, we may be able to suggest a work-around.

**Comment by benny856694** [comment]
> Please use the Fusion Log Viewer tool as mentioned above to determine what is missing. We don't support out of support OSs, but if you can determine what's not loading correctly, we may be able to suggest a work-around.

Do I have to install visual studio on the target machine to get this tool?
normally we won't install visual studio on the target machine

**Comment by MikeYeager** [comment]
@benny856694 Normally you would install it with VS, but there are some ways to do without. https://stackoverflow.com/questions/1012252/using-fuslogvw-exe-on-a-machine-with-no-visual-studio-installed

**Comment by benny856694** [comment]
> [@benny856694](https://github.com/benny856694) Normally you would install it with VS, but there are some ways to do without. https://stackoverflow.com/questions/1012252/using-fuslogvw-exe-on-a-machine-with-no-visual-studio-installed

I tried it seems nothing get logged

Steps:

1.  installed .net 4.8 sdk on target machine to get fuslogvw.exe.
2.  enable logging (see below image)
3.  run the photino app 
4.  the log windows is always empty

![Image](https://github.com/user-attachments/assets/ec98d2f4-bf62-41c3-b92f-5a5593b0b73b)

![Image](https://github.com/user-attachments/assets/3947b5ae-2e0b-4f68-a675-e146ca188f7e)

**Comment by MikeYeager** [comment]
@benny856694 It is a notoriously quirky utility. I've found that you have to log to a file, run your test, then quit the utility before it outputs anything. Please see if that works for you.

**Comment by benny856694** [comment]
After digging, I found the root cause:
api-ms-win-shcore-scaling-l1-1-1.dll doesn't exists on win7 x64, which is imported by Photino.Native.dll.

![Image](https://github.com/user-attachments/assets/f9bfd9f9-39d5-490a-a55f-e2552f2038c3)

**Comment by MikeYeager** [comment]
@benny856694 Thank you for tracking this down. This library (Shcore.lib) is used to return the DPI for attached monitors. This in turn is used to detect scaling on the monitors. It seems Windows 7 does not support this functionality. We know that some of our users rely on these DPI and scaling values, so we can't drop support for it without breaking code. One work-around we've seen mentioned is for you to copy the .dll from a later version of Windows to the Windows 7 installation, though it's not guaranteed to work. We don't know of a way to branch our code to not attempt loading the dll if it finds it's running on Windows 7. Perhaps someone in the community has an answer for that?

**Comment by benny856694** [comment]
I tried to download that DLL and put it inside the folder, no luck, I give up on Win7

**Comment by MikeYeager** [comment]
We're going to go ahead and close this one for now. Not sure if it still makes sense to support Win 7. Perhaps someone from the community can suggest a work-around. We need the DPI awareness in newer OS's, but it's not supported in Win 7. We're unsure if there is a way to prevent the app trying to load this DLL if running on Win 7. Any help is appreciated.
